{% set name = "ARIA-tools" %}
{% set version = "1.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aria-tools/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d92cd37d32ea6f4e26a5cbf6a007dcfde0bdd67d568ed9f8acba63f2142c954a

build:
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38 or win]
  # entry_points: 
  #   - ariaExtract.py = tools/bin/ariaExtract.py:main
  #   - ariaDownload.py = tools/bin/ariaDownload.py:main
  #   - ariaTSsetup.py = tools/bin/ariaTSsetup.py:main
  #   - ariaPlot = tools/bin/ariaPlot.py:main
  #   - ariaMisclosure.py = tools/bin/ariaMisclosure.py:main
  #   - ariaAOIassist.py = tools/bin/ariaAOIassist.py:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - pybind11 >=2.5.0
    - setuptools >61.0
    - setuptools_scm >6.2
    - python-build
    - numpy
    - cython
  run:
    - python
    - asf_search
    - cartopy
    - gdal >=3.4.1
    - h5py
    - joblib
    - matplotlib-base
    - netcdf4
    - pandas
    - xarray
    - rasterio
    - rioxarray
    - pip
    - pyproj
    - requests
    - scipy <1.10
    - mintpy
    - shapely

test:
  imports:
    - ARIAtools
  requires:
    - pip
  commands:
    - pip check
    # - ariaExtract.py -h
    # - ariaDownload.py -h
    # - ariaTSsetup.py -h
    # - ariaPlot -h
    # - ariaMisclosure.py -h
    # - ariaAOIassist.py -h

about:
  home: https://github.com/aria-tools/ARIA-tools
  summary: Advanced Rapid Imaging and Analysis Product Toolkit
  description: |
    ARIA-tools is an open-source package in Python which contains tools to 
    manipulate ARIA standard InSAR products. Its development was funded under
    the NASA Sea-level Change Team (NSLCT) program and the Earth Surface
    and Interior (ESI) program. U.S. Government sponsorship acknowledged.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/dbekaert/RAiDER-docs
  dev_url: https://github.com/aria-tools/ARIA-tools-docs

extra:
  recipe-maintainers:
    - sssangha
    - cmarshak
    - jhkennedy
    - dbekaert
